name: main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install FFmpeg - linux
        run: |
          sudo apt update
          sudo apt install software-properties-common -y
          sudo add-apt-repository ppa:savoury1/ffmpeg4 -y
          sudo add-apt-repository ppa:savoury1/ffmpeg5 -y
          sudo apt update
          sudo apt install ffmpeg -y
      - name: Build
        run: |
          dotnet build -c Release
      - name: Test
        run: |
          dotnet test -c Release
  windows-latest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          dotnet build -c Release
      - name: Codegen Build & Test
        run: |
          dotnet run -c Release --project Sdcb.FFmpeg.AutoGen --
          dotnet build Sdcb.FFmpeg
      - name: Test
        run: |
          dotnet test -c Release
      - uses: actions/upload-artifact@v3
        with:
          path: |
            Sdcb.FFmpeg/bin/Release/*.nupkg
            Sdcb.FFmpeg/bin/Release/*.snupkg
          if-no-files-found: error